### ISSUE TITLE
Extract common DataLink library and test suite

### ISSUE THREAD

**Issue by at88mph** [opencadc/dal#14]

**Comment by pdowler** [comment]
The basic DataLink class and code to write a VOTable could be be re-used but will take some re-org as they make some undocumented assumptions that are CADC-specific.

There are two ways to implement a sync web service like DataLink with opencadc libraries:
* implement a JobRunner and use cadc-uws-server to deploy a sync endpoint
* implement GetAction and PostAction classes and use cadc-rest

The caom2 datalink service implements a JobRunner (UWS) because it is simpler and you get to fully log all the jobs if you want to. I will try to extract a base implementation and I expect it will just have some abstract methods that are custom to the relevant back end query and storage system.

I will create the new library and do the basic refractoring on Friday 2019-06-07

**Comment by pdowler** [comment]
cadc-datalink-server library was extracted from caom2-datalink-server
